use block2::RcBlock;
use core_foundation::array::CFArray;
use core_foundation::base::{CFType, CFTypeRef, TCFType};
use core_foundation::boolean::CFBoolean;
use core_foundation::dictionary::{CFDictionary, CFDictionaryRef};
use core_foundation::number::CFNumber;
use core_foundation::runloop::CFRunLoop;
use core_foundation::string::{CFString, CFStringRef};
use core_graphics::event::{
    CGEvent, CGEventFlags, CGEventTap, CGEventTapLocation, CGEventTapOptions, CGEventTapPlacement,
    CGEventType, CallbackResult, EventField, KeyCode,
};
use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};
use objc2::rc::Retained;
use objc2::runtime::{Bool, ProtocolObject};
use objc2_app_kit::{
    NSApplicationActivationOptions, NSPasteboard, NSPasteboardItem, NSPasteboardTypeString,
    NSPasteboardWriting, NSRunningApplication, NSWorkspace,
};
use objc2_av_foundation::{AVAuthorizationStatus, AVCaptureDevice, AVMediaType, AVMediaTypeAudio};
use objc2_foundation::{NSArray, NSData, NSString, NSThread};
use std::panic::AssertUnwindSafe;
use std::process::Command;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, Instant};
use tauri::AppHandle;

const FUNCTION_KEY_CODE: i64 = 0x003f;
const SPACE_KEY_CODE: i64 = 0x0031;
const ESCAPE_KEY_CODE: i64 = 0x0035;
const PASTEBOARD_RESTORE_DELAY: Duration = Duration::from_millis(250);
const SYNTHETIC_KEY_DELAY: Duration = Duration::from_millis(5);
const PASTE_MENU_QUERY_TIMEOUT: Duration = Duration::from_millis(350);
const PASTE_MENU_QUERY_TIMEOUT_SECONDS: f32 = 0.10;
const PASTE_MENU_ACTION_TIMEOUT_SECONDS: f32 = 1.0;
const MAX_PASTE_MENU_NODES: usize = 512;
const MAX_PASTE_MENU_DEPTH: usize = 6;
const MAX_PASTEBOARD_SNAPSHOT_BYTES: usize = 64 * 1024 * 1024;
const TRANSIENT_PASTEBOARD_TYPE: &str = "org.nspasteboard.TransientType";
const CONCEALED_PASTEBOARD_TYPE: &str = "org.nspasteboard.ConcealedType";
const AUTO_GENERATED_PASTEBOARD_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
const AX_ERROR_SUCCESS: i32 = 0;
const AX_ERROR_CANNOT_COMPLETE: i32 = -25204;
const ANSI_V_KEY_CODE: i64 = 9;

struct PreparedPaste {
    previous_items: Vec<PasteboardItemSnapshot>,
    transcript_change_count: isize,
}

struct PasteboardItemSnapshot {
    representations: Vec<PasteboardRepresentation>,
}

struct PasteboardRepresentation {
    data_type: String,
    data: Vec<u8>,
}

#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    fn AXIsProcessTrustedWithOptions(options: CFDictionaryRef) -> bool;
    fn AXUIElementCreateApplication(pid: i32) -> CFTypeRef;
    fn AXUIElementCopyAttributeValue(
        element: CFTypeRef,
        attribute: CFStringRef,
        value: *mut CFTypeRef,
    ) -> i32;
    fn AXUIElementPerformAction(element: CFTypeRef, action: CFStringRef) -> i32;
    fn AXUIElementSetMessagingTimeout(element: CFTypeRef, timeout_in_seconds: f32) -> i32;
    static kAXTrustedCheckOptionPrompt: CFStringRef;
}

struct PasteMenuAttributes {
    menu_bar: CFString,
    children: CFString,
    command_char: CFString,
    command_virtual_key: CFString,
    command_modifiers: CFString,
    enabled: CFString,
    press: CFString,
}

impl PasteMenuAttributes {
    fn new() -> Self {
        Self {
            menu_bar: CFString::from_static_string("AXMenuBar"),
            children: CFString::from_static_string("AXChildren"),
            command_char: CFString::from_static_string("AXMenuItemCmdChar"),
            command_virtual_key: CFString::from_static_string("AXMenuItemCmdVirtualKey"),
            command_modifiers: CFString::from_static_string("AXMenuItemCmdModifiers"),
            enabled: CFString::from_static_string("AXEnabled"),
            press: CFString::from_static_string("AXPress"),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FnEvent {
    Ready,
    Pressed,
    Released,
    HandsFreeToggle,
    Cancel,
    Unavailable,
}

pub fn accessibility_trusted() -> bool {
    check_accessibility(false)
}

pub fn request_accessibility() {
    let _ = check_accessibility(true);
}

pub fn microphone_trusted() -> bool {
    microphone_permission() == AVAuthorizationStatus::Authorized
}

pub fn request_microphone() {
    let status = microphone_permission();
    if status == AVAuthorizationStatus::NotDetermined {
        prompt_for_microphone();
    } else if status != AVAuthorizationStatus::Authorized {
        let _ = Command::new("/usr/bin/open")
            .arg("x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone")
            .spawn();
    }
}

pub fn prompt_for_microphone_if_needed() {
    if microphone_permission() == AVAuthorizationStatus::NotDetermined {
        prompt_for_microphone();
    }
}

pub fn frontmost_application_pid() -> Option<i32> {
    NSWorkspace::sharedWorkspace()
        .frontmostApplication()
        .map(|application| application.processIdentifier())
}

pub fn activate_application(pid: i32) -> bool {
    NSRunningApplication::runningApplicationWithProcessIdentifier(pid).is_some_and(|application| {
        application.activateWithOptions(NSApplicationActivationOptions::empty())
    })
}

pub fn insert_text(app: &AppHandle, target_pid: i32, text: &str) -> Result<(), String> {
    if text.is_empty() {
        return Ok(());
    }
    if !accessibility_trusted() {
        return Err("Keyboard access is required to insert the transcript.".to_string());
    }

    let text_for_clipboard = text.to_string();
    let prepared = run_on_main_thread(app, move || prepare_paste_on_main(&text_for_clipboard))??;

    let paste_result = deliver_paste(target_pid);
    // Paste commands are handled synchronously in most apps, but a short
    // grace period also covers web views and terminal emulators that defer
    // their pasteboard read to the next run-loop turn.
    thread::sleep(PASTEBOARD_RESTORE_DELAY);

    let text_for_recovery = text.to_string();
    let restore_result = run_on_main_thread(app, move || {
        restore_pasteboard_on_main(prepared, &text_for_recovery)
    })?;

    if let Err(error) = paste_result {
        return Err(format!(
            "Could not paste automatically: {error} — transcript kept for recovery"
        ));
    }
    restore_result
}

fn prepare_paste_on_main(text: &str) -> Result<PreparedPaste, String> {
    let pasteboard = catch_objc_exception(NSPasteboard::generalPasteboard)?;
    let previous_items = catch_objc_exception(|| snapshot_pasteboard(&pasteboard))??;

    match catch_objc_exception(|| write_transcript_to_pasteboard(&pasteboard, text)) {
        Ok(Ok(transcript_change_count)) => Ok(PreparedPaste {
            previous_items,
            transcript_change_count,
        }),
        Ok(Err(error)) | Err(error) => {
            let _ = catch_objc_exception(|| restore_pasteboard(&pasteboard, &previous_items));
            Err(error)
        }
    }
}

fn restore_pasteboard_on_main(prepared: PreparedPaste, text: &str) -> Result<(), String> {
    let pasteboard = catch_objc_exception(NSPasteboard::generalPasteboard)?;
    let current_change_count = catch_objc_exception(|| pasteboard.changeCount())?;
    if current_change_count != prepared.transcript_change_count {
        // Never overwrite something copied while the paste was in flight.
        return Ok(());
    }

    let restore_result =
        catch_objc_exception(|| restore_pasteboard(&pasteboard, &prepared.previous_items));
    match restore_result {
        Ok(Ok(())) => Ok(()),
        Ok(Err(_)) | Err(_) => {
            // If restoration itself fails, keep the transcript recoverable
            // instead of leaving the clipboard empty.
            let _ = catch_objc_exception(|| write_transcript_to_pasteboard(&pasteboard, text));
            Err("Text was inserted, but the previous clipboard could not be restored.".to_string())
        }
    }
}

fn snapshot_pasteboard(pasteboard: &NSPasteboard) -> Result<Vec<PasteboardItemSnapshot>, String> {
    let Some(items) = pasteboard.pasteboardItems() else {
        return Ok(Vec::new());
    };

    let mut snapshot_bytes = 0;
    let mut snapshot = Vec::with_capacity(items.len());
    for item in items.to_vec() {
        let types = item.types().to_vec();
        let mut representations = Vec::with_capacity(types.len());
        for data_type in types {
            let Some(data) = item.dataForType(&data_type) else {
                return Err("Could not safely preserve the current clipboard.".to_string());
            };
            let bytes = data.to_vec();
            snapshot_bytes = checked_snapshot_size(snapshot_bytes, bytes.len())?;
            representations.push(PasteboardRepresentation {
                data_type: data_type.to_string(),
                data: bytes,
            });
        }
        if representations.is_empty() {
            return Err("Could not safely preserve the current clipboard.".to_string());
        }
        snapshot.push(PasteboardItemSnapshot { representations });
    }
    Ok(snapshot)
}

fn checked_snapshot_size(current: usize, additional: usize) -> Result<usize, String> {
    let total = current
        .checked_add(additional)
        .ok_or_else(|| "The current clipboard is too large to preserve safely.".to_string())?;
    if total > MAX_PASTEBOARD_SNAPSHOT_BYTES {
        Err("The current clipboard is too large to preserve safely.".to_string())
    } else {
        Ok(total)
    }
}

fn write_transcript_to_pasteboard(pasteboard: &NSPasteboard, text: &str) -> Result<isize, String> {
    let item = NSPasteboardItem::new();
    let string = NSString::from_str(text);
    let string_type = unsafe { NSPasteboardTypeString };
    if !item.setString_forType(&string, string_type) {
        return Err("Could not prepare the transcript for insertion.".to_string());
    }

    // These conventional marker types tell clipboard managers not to retain
    // this short-lived entry. Apps that do not recognize them simply ignore
    // them and read the normal string representation.
    let marker_value = NSString::from_str("");
    for marker in [
        TRANSIENT_PASTEBOARD_TYPE,
        CONCEALED_PASTEBOARD_TYPE,
        AUTO_GENERATED_PASTEBOARD_TYPE,
    ] {
        let marker_type = NSString::from_str(marker);
        let _ = item.setString_forType(&marker_value, &marker_type);
    }

    let object = ProtocolObject::from_ref(&*item);
    let objects = NSArray::from_slice(&[object]);
    pasteboard.clearContents();
    if !pasteboard.writeObjects(&objects) {
        return Err("Could not prepare the transcript for insertion.".to_string());
    }
    Ok(pasteboard.changeCount())
}

fn restore_pasteboard(
    pasteboard: &NSPasteboard,
    snapshot: &[PasteboardItemSnapshot],
) -> Result<(), String> {
    let restored_items = snapshot
        .iter()
        .map(|saved_item| {
            let item = NSPasteboardItem::new();
            for representation in &saved_item.representations {
                let data_type = NSString::from_str(&representation.data_type);
                let data = NSData::with_bytes(&representation.data);
                if !item.setData_forType(&data, &data_type) {
                    return Err("Could not reconstruct the previous clipboard.".to_string());
                }
            }
            Ok(item)
        })
        .collect::<Result<Vec<Retained<NSPasteboardItem>>, String>>()?;

    pasteboard.clearContents();
    if restored_items.is_empty() {
        return Ok(());
    }
    let objects = restored_items
        .iter()
        .map(|item| ProtocolObject::from_ref(&**item))
        .collect::<Vec<&ProtocolObject<dyn NSPasteboardWriting>>>();
    let objects = NSArray::from_slice(&objects);
    if pasteboard.writeObjects(&objects) {
        Ok(())
    } else {
        Err("Could not restore the previous clipboard.".to_string())
    }
}

fn catch_objc_exception<T>(operation: impl FnOnce() -> T) -> Result<T, String> {
    objc2::exception::catch(AssertUnwindSafe(operation))
        .map_err(|_| "macOS rejected clipboard access.".to_string())
}

pub fn copy_text(app: &AppHandle, text: &str) -> Result<(), String> {
    let text = text.to_string();
    run_on_main_thread(app, move || copy_text_on_main(&text))?
}

fn copy_text_on_main(text: &str) -> Result<(), String> {
    match objc2::exception::catch(|| copy_text_on_main_inner(text)) {
        Ok(result) => result,
        Err(_) => Err("macOS rejected clipboard access.".to_string()),
    }
}

fn copy_text_on_main_inner(text: &str) -> Result<(), String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    let string = NSString::from_str(text);
    let string_type = unsafe { NSPasteboardTypeString };
    if pasteboard.setString_forType(&string, string_type) {
        Ok(())
    } else {
        Err("Could not copy the transcript.".to_string())
    }
}

fn run_on_main_thread<T>(
    app: &AppHandle,
    operation: impl FnOnce() -> T + Send + 'static,
) -> Result<T, String>
where
    T: Send + 'static,
{
    if NSThread::isMainThread_class() {
        return Ok(operation());
    }

    let (sender, receiver) = mpsc::sync_channel(1);
    app.run_on_main_thread(move || {
        let _ = sender.send(operation());
    })
    .map_err(|error| format!("Could not schedule text delivery: {error}"))?;
    receiver
        .recv()
        .map_err(|_| "Text delivery stopped before it could finish.".to_string())
}

fn deliver_paste(target_pid: i32) -> Result<(), String> {
    // Invoking the app's own Paste menu item is the most direct cross-app
    // delivery route and continues to work when an app filters synthetic key
    // events. Apps without an accessible standard Paste command fall back to
    // a process-targeted Command-V event sequence.
    deliver_with_fallback(
        || press_paste_menu_item(target_pid),
        || press_paste_shortcut(target_pid),
    )
}

fn deliver_with_fallback(
    preferred: impl FnOnce() -> Result<(), String>,
    fallback: impl FnOnce() -> Result<(), String>,
) -> Result<(), String> {
    preferred().or_else(|_| fallback())
}

fn press_paste_menu_item(target_pid: i32) -> Result<(), String> {
    let application_ref = unsafe { AXUIElementCreateApplication(target_pid) };
    if application_ref.is_null() {
        return Err("Could not inspect the target app's Paste command".to_string());
    }
    let application = unsafe { CFType::wrap_under_create_rule(application_ref) };
    let query_timeout = unsafe {
        AXUIElementSetMessagingTimeout(application_ref, PASTE_MENU_QUERY_TIMEOUT_SECONDS)
    };
    if query_timeout != AX_ERROR_SUCCESS {
        return Err("Could not inspect the target app's Paste command".to_string());
    }

    let attributes = PasteMenuAttributes::new();
    let menu_bar = ax_attribute(&application, &attributes.menu_bar)
        .map_err(|_| "The target app does not expose a menu bar".to_string())?;
    let deadline = Instant::now() + PASTE_MENU_QUERY_TIMEOUT;
    let mut remaining_nodes = MAX_PASTE_MENU_NODES;
    let paste_item =
        find_paste_menu_item(&menu_bar, &attributes, 0, &mut remaining_nodes, deadline)
            .ok_or_else(|| "The target app does not expose a standard Paste command".to_string())?;

    // Give the target's menu action more time than the bounded tree lookup.
    // A timeout is indeterminate according to macOS: the action might still
    // have run, so treating it as delivered avoids a duplicate fallback paste.
    let _ = unsafe {
        AXUIElementSetMessagingTimeout(application_ref, PASTE_MENU_ACTION_TIMEOUT_SECONDS)
    };
    let result = unsafe {
        AXUIElementPerformAction(
            paste_item.as_CFTypeRef(),
            attributes.press.as_concrete_TypeRef(),
        )
    };
    if matches!(result, AX_ERROR_SUCCESS | AX_ERROR_CANNOT_COMPLETE) {
        Ok(())
    } else {
        Err(format!(
            "The target app rejected its Paste command ({result})"
        ))
    }
}

fn find_paste_menu_item(
    element: &CFType,
    attributes: &PasteMenuAttributes,
    depth: usize,
    remaining_nodes: &mut usize,
    deadline: Instant,
) -> Option<CFType> {
    if *remaining_nodes == 0 || Instant::now() >= deadline {
        return None;
    }
    *remaining_nodes -= 1;

    if is_enabled_plain_paste_item(element, attributes) {
        return Some(element.clone());
    }
    if depth >= MAX_PASTE_MENU_DEPTH {
        return None;
    }

    let children = ax_attribute(element, &attributes.children)
        .ok()?
        .downcast::<CFArray>()?;
    for child_ref in children.iter() {
        if (*child_ref).is_null() {
            continue;
        }
        let child = unsafe { CFType::wrap_under_get_rule(*child_ref) };
        if let Some(paste_item) =
            find_paste_menu_item(&child, attributes, depth + 1, remaining_nodes, deadline)
        {
            return Some(paste_item);
        }
    }
    None
}

fn is_enabled_plain_paste_item(element: &CFType, attributes: &PasteMenuAttributes) -> bool {
    let command_char = ax_attribute(element, &attributes.command_char)
        .ok()
        .and_then(|value| value.downcast::<CFString>())
        .map(|value| value.to_string());
    let virtual_key = ax_attribute(element, &attributes.command_virtual_key)
        .ok()
        .and_then(|value| value.downcast::<CFNumber>())
        .and_then(|value| value.to_i64());
    let modifiers = ax_attribute(element, &attributes.command_modifiers)
        .ok()
        .and_then(|value| value.downcast::<CFNumber>())
        .and_then(|value| value.to_i64());
    let enabled = ax_attribute(element, &attributes.enabled)
        .ok()
        .and_then(|value| value.downcast::<CFBoolean>())
        .is_some_and(|value| value == CFBoolean::true_value());

    enabled && is_plain_paste_shortcut(command_char.as_deref(), virtual_key, modifiers)
}

fn is_plain_paste_shortcut(
    command_char: Option<&str>,
    virtual_key: Option<i64>,
    modifiers: Option<i64>,
) -> bool {
    let is_v = command_char.is_some_and(|value| value.eq_ignore_ascii_case("v"))
        || virtual_key == Some(ANSI_V_KEY_CODE);
    is_v && modifiers == Some(0)
}

fn ax_attribute(element: &CFType, attribute: &CFString) -> Result<CFType, i32> {
    let mut value = std::ptr::null();
    let result = unsafe {
        AXUIElementCopyAttributeValue(
            element.as_CFTypeRef(),
            attribute.as_concrete_TypeRef(),
            &mut value,
        )
    };
    if result != AX_ERROR_SUCCESS || value.is_null() {
        Err(result)
    } else {
        Ok(unsafe { CFType::wrap_under_create_rule(value) })
    }
}

fn press_paste_shortcut(target_pid: i32) -> Result<(), String> {
    let source = CGEventSource::new(CGEventSourceStateID::HIDSystemState)
        .map_err(|_| "Could not create a keyboard event source".to_string())?;
    let command_down = CGEvent::new_keyboard_event(source.clone(), KeyCode::COMMAND, true)
        .map_err(|_| "Could not create the Command key-down event".to_string())?;
    let paste_down = CGEvent::new_keyboard_event(source.clone(), KeyCode::ANSI_V, true)
        .map_err(|_| "Could not create the V key-down event".to_string())?;
    let paste_up = CGEvent::new_keyboard_event(source.clone(), KeyCode::ANSI_V, false)
        .map_err(|_| "Could not create the V key-up event".to_string())?;
    let command_up = CGEvent::new_keyboard_event(source, KeyCode::COMMAND, false)
        .map_err(|_| "Could not create the Command key-up event".to_string())?;

    command_down.set_flags(CGEventFlags::CGEventFlagCommand);
    paste_down.set_flags(CGEventFlags::CGEventFlagCommand);
    paste_up.set_flags(CGEventFlags::CGEventFlagCommand);
    command_up.set_flags(CGEventFlags::CGEventFlagNull);

    for event in [&command_down, &paste_down, &paste_up, &command_up] {
        event.post_to_pid(target_pid);
        thread::sleep(SYNTHETIC_KEY_DELAY);
    }
    Ok(())
}

pub fn start_fn_monitor(
    dictation_active: Arc<AtomicBool>,
    callback: impl Fn(FnEvent) + Send + Sync + 'static,
) {
    let (event_sender, event_receiver) = mpsc::channel();
    thread::spawn(move || {
        for event in event_receiver {
            callback(event);
        }
    });

    thread::spawn(move || {
        loop {
            if !accessibility_trusted() {
                thread::sleep(Duration::from_millis(500));
                continue;
            }

            let fn_is_down = AtomicBool::new(false);
            let hands_free_space_is_down = AtomicBool::new(false);
            let callback_sender = event_sender.clone();
            let ready_sender = event_sender.clone();
            let dictation_active = dictation_active.clone();
            let result = CGEventTap::with_enabled(
                CGEventTapLocation::HID,
                CGEventTapPlacement::HeadInsertEventTap,
                // An active pass-through tap is authorized by Accessibility.
                // A ListenOnly tap would require a second Input Monitoring grant.
                CGEventTapOptions::Default,
                vec![
                    CGEventType::FlagsChanged,
                    CGEventType::KeyDown,
                    CGEventType::KeyUp,
                ],
                move |_proxy, event_type, event| {
                    let event_type = event_type as u32;
                    let key_code =
                        event.get_integer_value_field(EventField::KEYBOARD_EVENT_KEYCODE);
                    let flags_show_fn = event
                        .get_flags()
                        .contains(CGEventFlags::CGEventFlagSecondaryFn);

                    if key_code == ESCAPE_KEY_CODE
                        && event_type == CGEventType::KeyDown as u32
                        && dictation_active.load(Ordering::Acquire)
                    {
                        let _ = callback_sender.send(FnEvent::Cancel);
                        return CallbackResult::Drop;
                    }

                    if key_code == SPACE_KEY_CODE {
                        if event_type == CGEventType::KeyDown as u32
                            && fn_is_down.load(Ordering::Acquire)
                        {
                            if !hands_free_space_is_down.swap(true, Ordering::AcqRel) {
                                let _ = callback_sender.send(FnEvent::HandsFreeToggle);
                            }
                            return CallbackResult::Drop;
                        }
                        if event_type == CGEventType::KeyUp as u32
                            && hands_free_space_is_down.swap(false, Ordering::AcqRel)
                        {
                            return CallbackResult::Drop;
                        }
                    }

                    let next_state = if key_code == FUNCTION_KEY_CODE
                        && event_type == CGEventType::KeyDown as u32
                    {
                        Some(true)
                    } else if key_code == FUNCTION_KEY_CODE
                        && event_type == CGEventType::KeyUp as u32
                    {
                        Some(false)
                    } else if event_type == CGEventType::FlagsChanged as u32
                        && (key_code == FUNCTION_KEY_CODE
                            || flags_show_fn != fn_is_down.load(Ordering::Relaxed))
                    {
                        Some(flags_show_fn)
                    } else {
                        None
                    };

                    if let Some(is_down) = next_state {
                        let was_down = fn_is_down.swap(is_down, Ordering::AcqRel);
                        if is_down != was_down {
                            let _ = callback_sender.send(if is_down {
                                FnEvent::Pressed
                            } else {
                                FnEvent::Released
                            });
                        }
                    }
                    CallbackResult::Keep
                },
                move || {
                    let _ = ready_sender.send(FnEvent::Ready);
                    CFRunLoop::run_current();
                },
            );

            if result.is_err() {
                let _ = event_sender.send(FnEvent::Unavailable);
                thread::sleep(Duration::from_secs(1));
            }
        }
    });
}

fn check_accessibility(show_prompt: bool) -> bool {
    let key = unsafe { CFString::wrap_under_get_rule(kAXTrustedCheckOptionPrompt) };
    let value = if show_prompt {
        CFBoolean::true_value()
    } else {
        CFBoolean::false_value()
    };
    let options = CFDictionary::from_CFType_pairs(&[(key, value)]);
    unsafe { AXIsProcessTrustedWithOptions(options.as_concrete_TypeRef()) }
}

fn microphone_permission() -> AVAuthorizationStatus {
    unsafe { AVCaptureDevice::authorizationStatusForMediaType(audio_media_type()) }
}

fn prompt_for_microphone() {
    let completion = RcBlock::new(|_granted: Bool| {});
    unsafe {
        AVCaptureDevice::requestAccessForMediaType_completionHandler(
            audio_media_type(),
            &completion,
        );
    }
}

fn audio_media_type() -> &'static AVMediaType {
    unsafe { AVMediaTypeAudio.expect("AVFoundation did not provide its audio media type") }
}

#[cfg(test)]
mod tests {
    use super::{
        MAX_PASTEBOARD_SNAPSHOT_BYTES, NSArray, NSData, NSPasteboard, NSPasteboardItem,
        NSPasteboardTypeString, NSPasteboardWriting, NSString, ProtocolObject,
        catch_objc_exception, checked_snapshot_size, deliver_with_fallback,
        is_plain_paste_shortcut, restore_pasteboard, snapshot_pasteboard,
        write_transcript_to_pasteboard,
    };
    use std::cell::Cell;

    #[test]
    fn clipboard_snapshot_accepts_the_size_limit() {
        assert_eq!(
            checked_snapshot_size(MAX_PASTEBOARD_SNAPSHOT_BYTES - 1, 1),
            Ok(MAX_PASTEBOARD_SNAPSHOT_BYTES)
        );
    }

    #[test]
    fn clipboard_snapshot_rejects_oversized_or_overflowing_data() {
        assert!(checked_snapshot_size(MAX_PASTEBOARD_SNAPSHOT_BYTES, 1).is_err());
        assert!(checked_snapshot_size(usize::MAX, 1).is_err());
    }

    #[test]
    fn paste_shortcut_matches_only_plain_command_v() {
        assert!(is_plain_paste_shortcut(Some("v"), None, Some(0)));
        assert!(is_plain_paste_shortcut(Some("V"), None, Some(0)));
        assert!(is_plain_paste_shortcut(None, Some(9), Some(0)));
        assert!(!is_plain_paste_shortcut(Some("v"), None, Some(1)));
        assert!(!is_plain_paste_shortcut(Some("c"), None, Some(0)));
        assert!(!is_plain_paste_shortcut(Some("v"), None, None));
    }

    #[test]
    fn delivery_prefers_the_accessible_command_and_falls_back_by_capability() {
        let fallback_called = Cell::new(false);
        assert_eq!(
            deliver_with_fallback(
                || Ok(()),
                || {
                    fallback_called.set(true);
                    Ok(())
                },
            ),
            Ok(())
        );
        assert!(!fallback_called.get());

        assert_eq!(
            deliver_with_fallback(
                || Err("menu unavailable".to_string()),
                || {
                    fallback_called.set(true);
                    Ok(())
                },
            ),
            Ok(())
        );
        assert!(fallback_called.get());
    }

    #[test]
    #[ignore = "NSPasteboard integration must be run on a Cocoa main thread"]
    fn clipboard_round_trip_reconstructs_rich_items() {
        let pasteboard = catch_objc_exception(NSPasteboard::pasteboardWithUniqueName).unwrap();
        let rich_type = NSString::from_str("public.rtf");
        let rich_bytes = b"{\\rtf1\\ansi FnScribe clipboard test}";

        catch_objc_exception(|| {
            let item = NSPasteboardItem::new();
            let text = NSString::from_str("original clipboard text");
            let string_type = unsafe { NSPasteboardTypeString };
            assert!(item.setString_forType(&text, string_type));
            assert!(item.setData_forType(&NSData::with_bytes(rich_bytes), &rich_type));
            let object: &ProtocolObject<dyn NSPasteboardWriting> = ProtocolObject::from_ref(&*item);
            let objects = NSArray::from_slice(&[object]);
            pasteboard.clearContents();
            assert!(pasteboard.writeObjects(&objects));
        })
        .unwrap();

        let snapshot = catch_objc_exception(|| snapshot_pasteboard(&pasteboard))
            .unwrap()
            .unwrap();
        catch_objc_exception(|| write_transcript_to_pasteboard(&pasteboard, "temporary"))
            .unwrap()
            .unwrap();
        catch_objc_exception(|| restore_pasteboard(&pasteboard, &snapshot))
            .unwrap()
            .unwrap();

        catch_objc_exception(|| {
            let items = pasteboard.pasteboardItems().unwrap().to_vec();
            assert_eq!(items.len(), 1);
            let string_type = unsafe { NSPasteboardTypeString };
            assert_eq!(
                items[0].stringForType(string_type).unwrap().to_string(),
                "original clipboard text"
            );
            assert_eq!(
                items[0].dataForType(&rich_type).unwrap().to_vec(),
                rich_bytes
            );
        })
        .unwrap();
    }
}
